PizzaStore/Models/Order.cs
using PizzaStore.Areas.Identity.Data;

namespace PizzaStore.Models
{
    public class Order
    {
        public int Id { get; set; }
        public String OrderNumber { get; set; } = String.Empty;
        public DateTime CreatedDate { get; set; }
        public String OrderStatus { get; set; } = string.Empty;
        public double Total { get; set; }
        public PizzaStoreUser PizzaStoreUser { get; set; }  
        public string UserId { get; set; }
    }
}

PizzaStore/Controllers/OrderDetailsController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PizzaStore.Areas.Identity.Data;
using PizzaStore.Data;
using PizzaStore.Models;
using System.Linq;
using System.Reflection.Metadata;

namespace PizzaStore.Controllers
{
    public class OrderDetailsController : Controller
    {
        private readonly PizzaStoreContext _context;
        private readonly UserManager<PizzaStoreUser> _user;

        public OrderDetailsController(PizzaStoreContext context, UserManager<PizzaStoreUser> user)
        {
            _context = context;
            _user = user;
        }

        public IActionResult OrderDetails(int orderId)
        {
            var details = _context.details
        .Where(q => q.OrderId == orderId)
        .Join(
            _context.products,
            details => details.ProductId,
            product => product.Id,
            (details, product) => new DetailsProductViewModel { Details = details, Product = product }
        )
        .ToList();

            return View(details);
        }

        public IActionResult DeleteOrder(int orderId)
        {
            var order = _context.orders.Find(orderId);
            if (order != null)
            {
                _context.orders.Remove(order);
                var details = _context.details
                    .Where(q => q.OrderId == orderId);
                _context.SaveChanges();

                foreach(var item in details)
                {
                    _context.details.Remove(item);
                    _context.SaveChanges();
                }
            }

            return RedirectToAction("Index","Orders");
        }

    }
}

PizzaStore/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PizzaStore.Areas.Identity.Data;
using PizzaStore.Data;

namespace PizzaStore.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {

        private readonly PizzaStoreContext _context;
        private readonly UserManager<PizzaStoreUser> _UserManager;
        public OrdersController(PizzaStoreContext context, UserManager<PizzaStoreUser> UserManager)
        {
            _context = context;
            _UserManager = UserManager;

        }
        public async Task<IActionResult> Index()
        {
            string UserId = _UserManager.GetUserId(User);

            return _context.products != null ?
                           View(await _context.orders.Where(q => q.UserId == UserId).ToListAsync()) :
                           Problem("Entity set 'PizzaStoreContext.products'  is null.");
        }
    }
}

PizzaStore/Views/Orders/Index.cshtml
@model IEnumerable<PizzaStore.Models.Order>



@*    <section class="section section-feature pb-0">
        <div class="container w-md-70">
            <div class="card card-bordered card-preview">
                <div class="card-inner">
                <table class="datatable-init-export nowrap table" data-export-title="Exporter">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Number</th>
                                <th>Status</th>
                                <th>Date</th>
                                <th> &nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.OrderNumber</td>
                                    <td>@item.OrderStatus</td>
                                    <td>@item.CreatedDate.Date</td>
                                    <td class="text-center">
                                    <a asp-action="DeleteOrder" asp-route-orderId="@item.Id" asp-controller="OrderDetails">delete</a>
                                    <a asp-action="OrderDetails" asp-route-orderId="@item.Id" asp-controller="OrderDetails">more</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div><!-- .card-preview -->
        </div>
    </section>
*@



<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-sm-6 col-lg-4 col-xxl-3 w-250px">
            <div class="card card-bordered h-100">
                <div class="card-inner">
                    <div class="project">
                        <div class="project-head">
                            <a class="project-title">
                                <div class="project-info">
                                    <h6 class="title">@item.OrderNumber</h6><span class="sub-text">@item.CreatedDate.ToShortDateString()</span>
                                </div>
                            </a>
                            <div class="drodown">
                                <a href="#" class="dropdown-toggle btn btn-sm btn-icon btn-trigger mt-n1 me-n1"
                                   data-bs-toggle="dropdown"><em class="icon ni ni-more-h"></em></a>
                                <div class="dropdown-menu dropdown-menu-end">
                                    <ul class="link-list-opt no-bdr">
                                        <li>
                                            <a asp-action="OrderDetails" asp-route-orderId="@item.Id" asp-controller="OrderDetails">
                                                <em class="icon ni ni-eye"></em>
                                                <span>View Order</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a asp-action="DeleteOrder" asp-route-orderId="@item.Id" asp-controller="OrderDetails">
                                                <em class="icon ni ni-trash"></em>
                                                <span>Delete Order</span>

                                            </a>
                                        </li>

                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="project-details">
                            <h3 class="text-success">$ @item.Total</h3>
                        </div>
                        <div class="project-meta">
                            <ul class="project-users g-1">
                                <li>
                                    <div class="user-avatar sm bg-white"><img src="~/images/hot-tasty-pizza-png.png" alt=""></div>
                                </li>
                            </ul><span class="badge badge-dim bg-warning">
                                <em class="icon ni ni-clock"></em><span>
                                    @item.OrderStatus
                                </span>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>