PizzaStore/Models/Cart.cs
namespace PizzaStore.Models
{
    public class Cart
    {
        public List<CartItem> Items { get; set; } = new List<CartItem>();

        public void AddItem(CartItem item)
        {
            // Check if the item already exists in the cart
            var existingItem = Items.FirstOrDefault(i => i.Product.Id == item.Product.Id);
            if (existingItem != null)
            {
                // Increment the quantity of the existing item
                existingItem.Quantity++;
            }
            else
            {
                // Add the item to the cart
                Items.Add(item);
            }
        }
    }
}

PizzaStore/Controllers/AboutUsController.cs
using Microsoft.AspNetCore.Mvc;

namespace PizzaStore.Controllers
{
    public class AboutUsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PizzaStore/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PizzaStore.Areas.Identity.Data;
using PizzaStore.Data;
using PizzaStore.Models;
using PizzaStore.Utilities;

namespace PizzaStore.Controllers
{
    public class CartController : Controller
    {
        private readonly PizzaStoreContext _context;
        private readonly UserManager<PizzaStoreUser> _user;
        private SignInManager<PizzaStoreUser> _signInManager;

        public CartController(PizzaStoreContext context, UserManager<PizzaStoreUser> user, SignInManager<PizzaStoreUser> signInManager)
        {
            _context = context;
            _user = user;
            _signInManager = signInManager;

        }
        public IActionResult Index()
        {
            var cart = HttpContext.Session.GetObjectFromJson<Cart>("Cart") ?? new Cart();
            return View(cart);
        }

        public IActionResult ClearCart ()
        {
            HttpContext.Session.Remove("Cart");
            return RedirectToAction("Index");
        }

        public IActionResult AddToCart(int Id)
        {

            var cart = HttpContext.Session.GetObjectFromJson<Cart>("Cart") ?? new Cart();
            
            var product = _context.products.Find(Id);
            if (product != null)
            {
                CartItem item = new CartItem();
                item.Product = product;
                cart.AddItem(item);
            }

            HttpContext.Session.SetObjectAsJson("Cart", cart);
            return Json(cart);
        }

        //public IActionResult ModifyQte(int cartValue, int productId)
        //{
        //    var cart = HttpContext.Session.GetObjectFromJson<Cart>("Cart");
        //    if (cart == null) {
        //        return RedirectToAction("index");
        //    }
        //    var cartItem = cart.Items.FirstOrDefault(x => x.Product.Id == productId);
        //    if (cartItem != null)
        //    {
        //        cart.Items.Remove(cartItem);
        //        cartItem.Quantity = cartValue;
        //        cart.Items.Add(cartItem);
        //        HttpContext.Session.SetObjectAsJson("Cart", cart);
        //    }

        //    return RedirectToAction("Index");
        //}


        public IActionResult RemoveOne(int productId)
        {
            var cart = HttpContext.Session.GetObjectFromJson<Cart>("Cart");
            if (cart == null)
            {
                return RedirectToAction("index");
            }
            var cartItem = cart.Items.FirstOrDefault(x => x.Product.Id == productId);
            if (cartItem != null)
            {
                cart.Items.Remove(cartItem);
                cartItem.Quantity--;
                cart.Items.Add(cartItem);
                HttpContext.Session.SetObjectAsJson("Cart", cart);
            }

            return RedirectToAction("Index");
        }


        public IActionResult AddOne(int productId)
        {
            var cart = HttpContext.Session.GetObjectFromJson<Cart>("Cart");
            if (cart == null)
            {
                return RedirectToAction("index");
            }
            var cartItem = cart.Items.FirstOrDefault(x => x.Product.Id == productId);
            if (cartItem != null)
            {
                cart.Items.Remove(cartItem);
                cartItem.Quantity++;
                cart.Items.Add(cartItem);
                HttpContext.Session.SetObjectAsJson("Cart", cart);
            }

            return RedirectToAction("Index");
        }

        public IActionResult RemoveFromCart(int id)
        {
            var cart = HttpContext.Session.GetObjectFromJson<Cart>("Cart") ?? new Cart();
            // Remove the item with the specified productId from the cart
            var item = cart.Items.Find(x => x.Product.Id == id);
            if (item != null)
            {
                cart.Items.Remove(item);
            }

            HttpContext.Session.SetObjectAsJson("Cart", cart);
            return RedirectToAction("Index");
        }
    }
}

PizzaStore/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PizzaStore.Areas.Identity.Data;
using PizzaStore.Data;

namespace PizzaStore.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {

        private readonly PizzaStoreContext _context;
        private readonly UserManager<PizzaStoreUser> _UserManager;
        public OrdersController(PizzaStoreContext context, UserManager<PizzaStoreUser> UserManager)
        {
            _context = context;
            _UserManager = UserManager;

        }
        public async Task<IActionResult> Index()
        {
            string UserId = _UserManager.GetUserId(User);

            return _context.products != null ?
                           View(await _context.orders.Where(q => q.UserId == UserId).ToListAsync()) :
                           Problem("Entity set 'PizzaStoreContext.products'  is null.");
        }
    }
}

PizzaStore/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PizzaStore.Data;
using PizzaStore.Models;

namespace PizzaStore.Controllers
{
    
    public class ProductsController : Controller
    {
        private readonly PizzaStoreContext _context;

        public ProductsController(PizzaStoreContext context)
        {
            _context = context;
        }


        // GET: Products
        public async Task<IActionResult> Index()
        {
              return _context.products != null ? 
                          View(await _context.products.ToListAsync()) :
                          Problem("Entity set 'PizzaStoreContext.products'  is null.");
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.products == null)
            {
                return NotFound();
            }

            var product = await _context.products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Price")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.products == null)
            {
                return NotFound();
            }

            var product = await _context.products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Price")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.products == null)
            {
                return NotFound();
            }

            var product = await _context.products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.products == null)
            {
                return Problem("Entity set 'PizzaStoreContext.products'  is null.");
            }
            var product = await _context.products.FindAsync(id);
            if (product != null)
            {
                _context.products.Remove(product);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
          return (_context.products?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

PizzaStore/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PizzaStore.Areas.Identity.Data;
using PizzaStore.Data;

namespace PizzaStore.Controllers
{
    public class ProfileController : Controller
    {
        private readonly PizzaStoreContext _context;
        private readonly UserManager<PizzaStoreUser> _UserManager;
        public ProfileController(PizzaStoreContext context, UserManager<PizzaStoreUser> UserManager)
        {
            _context = context;
            _UserManager = UserManager;

        }
        public IActionResult Index()
        {
            string UserId = _UserManager.GetUserId(User);

            var user = _context.Users.Find(UserId);
            return View(user);
        }
    }
}

PizzaStore/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using PizzaStore.Areas.Identity.Data

@inject SignInManager<PizzaStoreUser> SignInManager
@inject UserManager<PizzaStoreUser> UserManager
@using System.Security.Claims

@{
    //string Username = Context.Session.GetString("Username");
    IgnoreSection("Scripts");
}



<!DOCTYPE html>
<html lang="zxx" class="js">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Page Title  -->
    <title>Pizza Shop</title>
    <!-- StyleSheets  -->
    <link rel="stylesheet" href="~/css/dashlite.css">
    <link rel="stylesheet" href="~/css/StyleSheet.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>

<body class="nk-body npc-invest bg-lighter">

    <div class="nk-app-root">
        <!-- wrap s -->
        <div class="nk-wrap ">
            <!-- main header s -->
            <div class="nk-header nk-header-fluid is-dark">
                <div class="container-xl wide-xl">
                    <div class="nk-header-wrap">
                        <div class="nk-menu-trigger me-sm-2 d-lg-none">
                            <a href="#" class="nk-nav-toggle nk-quick-nav-icon" data-target="headerNav"><em class="icon ni ni-menu"></em></a>
                        </div>
                        <div class="nk-header-brand">
                            <a asp-controller="Home" asp-action="Index" class="logo-link">
                                @*<img class="logo-light logo-img" src="~/images/logo.png">*@
                            </a>
                        </div><!-- .nk-header-brand -->
                        <div class="nk-header-menu" data-content="headerNav">
                            <div class="nk-header-mobile">
                                <div class="nk-header-brand">
                                    <a asp-controller="Home" asp-action="Index" class="logo-link">
                                    </a>
                                </div>
                                <div class="nk-menu-trigger me-n2">
                                    <a href="#" class="nk-nav-toggle nk-quick-nav-icon" data-target="headerNav"><em class="icon ni ni-arrow-left"></em></a>
                                </div>
                            </div>

                            @*-------------------------------- THIS IS THE NAV BAR -------------------------------------*@

                            <ul class="nk-menu nk-menu-main ui-s2">
                                <li class="nk-menu-item">
                                    <a asp-controller="Products" asp-action="Index" class="nk-menu-link page-link">
                                        <span class="nk-menu-text">Shop</span>
                                    </a>
                                </li><!-- .nk-menu-item -->
                                @if (SignInManager.IsSignedIn(User))
                                {
                                    <li class="nk-menu-item">
                                        <a asp-controller="Orders" asp-action="Index" class="nk-menu-link page-link">
                                            <span class="nk-menu-text">My Orders</span>
                                        </a>
                                    </li><!-- .nk-menu-item -->

                                    <li class="nk-menu-item">
                                        <a asp-controller="Profile" asp-action="Index" class="nk-menu-link page-link">
                                            <span class="nk-menu-text">My Profile</span>
                                        </a>
                                    </li><!-- .nk-menu-item -->

                                    
                                }
                                <li class="nk-menu-item">
                                    <a asp-action="Index" asp-controller="AboutUs" class="nk-menu-link page-link">
                                        <span class="nk-menu-text">About US</span>
                                    </a>
                                </li><!-- .nk-menu-item -->
                                @*-------------------------------- THIS IS THE NAV BAR -------------------------------------*@

                            </ul><!-- .nk-menu -->
                        </div><!-- .nk-header-menu -->
                        <div class="nk-header-tools">
                            <ul class="nk-quick-nav">
                                <li class="dropdown notification-dropdown">
                                    <a asp-controller="Cart" asp-action="Index" class="nk-quick-nav-icon">

                                        @*Add this class if the cart got items
                                        icon-status icon-status-info*@ 
                                        
                                        <em class="icon ni ni-cart"></em>
                                    </a>
                                </li><!-- .dropdown -->
                                @if (SignInManager.IsSignedIn(User))
                                {
                                    <li class="dropdown user-dropdown order-sm-first">
                                        <a href="#" class="dropdown-toggle" data-bs-toggle="dropdown">
                                            <div class="user-toggle">
                                                <div class="user-avatar sm">
                                                    <em class="icon ni ni-user-alt"></em>
                                                </div>
                                            </div>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-md dropdown-menu-end dropdown-menu-s1 is-light">
                                            <div class="dropdown-inner">
                                                <ul class="link-list">
                                                    <li><a asp-controller="Profile" asp-action="Index"><em class="icon ni ni-user-alt"></em><span>View Profile</span></a></li>
                                                    <li><a asp-area="Identity" asp-page="/Account/Manage/Email"><em class="icon ni ni-setting-alt"></em><span>Account Setting</span></a></li>
                                                    @*<li><a href="html/user-profile-activity.html"><em class="icon ni ni-activity-alt"></em><span>Login Activity</span></a></li>*@
                                                    @*<li><a class="dark-mode-switch" href="#"><em class="icon ni ni-moon"></em><span>Dark Mode</span></a></li>*@
                                                </ul>
                                            </div>
                                            <div class="dropdown-inner">
                                                <ul class="link-list">
                                                    <li>
                                                        <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                                            <button id="logout" type="submit" class="menu-link btn btn-outline-primary ms-2 ms-md-0"><em class="icon ni ni-signout"></em><span>Sign out</span></button>
                                                        </form>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </li><!-- .dropdown -->
                                }
                                else
                                {
                                    <li class="dropdown user-dropdown">
                                        <a class="btn btn-primary px-3 py-1" id="login" asp-area="Identity" asp-page="/Account/Login">
                                            log in
                                        </a>
                                    </li>
                                }
                            </ul><!-- .nk-quick-nav -->
                        </div><!-- .nk-header-tools -->
                    </div><!-- .nk-header-wrap -->
                </div><!-- .container-fliud -->
            </div>
            <!-- main header e -->
            <!-- content s -->
            <div class="nk-content nk-content-fluid">
                <div class="container-xl wide-xl">
                    <div class="nk-content-inner">
                        <div class="nk-content-body">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
            <!-- content e -->
            <!-- footer s -->
            <div class="nk-footer nk-footer-fluid bg-lighter">
                <div class="container-xl">
                    <div class="nk-footer-wrap">
                        <div class="nk-footer-copyright">
                            &copy; 2022 DashLite. Template by <a href="https://softnio.com" target="_blank">Softnio</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- footer e -->
        </div>
        <!-- wrap e -->
    </div>
    <!-- app-root e -->

    <!-- JavaScript -->
    <script src="~/js/bundle.js"></script>
    <script src="~/js/scripts.js"></script>
    <script src="~/js/app.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
   
</body>

</html>























@*<div class="nk-header-tools">
    <ul class="nk-quick-nav">
        <li class="dropdown notification-dropdown">
            <a asp-controller="Cart" asp-action="Index" class="dropdown-toggle nk-quick-nav-icon">
                <div class="icon-status icon-status-info"><em class="icon ni ni-cart"></em></div>
            </a>
        </li>
        @if (SignInManager.IsSignedIn(User))
        {
            <li class="dropdown user-dropdown">
                <a href="#" class="dropdown-toggle me-n1" data-bs-toggle="dropdown">
                    <div class="user-toggle">
                        <div class="user-avatar sm">
                            <em class="icon ni ni-user-alt"></em>
                        </div>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-md dropdown-menu-end">
                    <div class="dropdown-inner">
                        <ul class="link-list">
                            <li><a href="html/user-profile-regular.html"><em class="icon ni ni-user-alt"></em><span>View Profile</span></a></li>
                            <li><a href="html/user-profile-setting.html"><em class="icon ni ni-setting-alt"></em><span>Account Setting</span></a></li>
                        </ul>
                    </div>
                    <div class="dropdown-inner">
                        <ul class="link-list">
                            <li>
                                <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                    <button id="logout" type="submit" class="menu-link btn btn-outline-primary ms-2 ms-md-0"><em class="icon ni ni-signout"></em><span>Sign out</span></button>
                                </form>
                            </li>
                        </ul>
                    </div>
                </div>
            </li>
        }
        else
        {
            <li class="dropdown user-dropdown">
                <a class="btn btn-primary px-3 py-1" id="login" asp-area="Identity" asp-page="/Account/Login">
                    log in
                </a>
            </li>
        }
    </ul>
</div>*@

PizzaStore/Views/Shared/_auth.cshtml
<!DOCTYPE html>
<html lang="zxx" class="js">

<head>
    <meta charset="utf-8">
    <meta name="author" content="Softnio">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A powerful and conceptual apps base dashboard template that especially build for developers and programmers.">
    <!-- Fav Icon  -->
    <link rel="shortcut icon" href="./images/favicon.png">
    <!-- Page Title  -->
    <title>Login | DashLite Admin Template</title>
    <!-- StyleSheets  -->
    <link rel="stylesheet" href="~/css/dashlite.css">
</head>

<body class="nk-body ui-rounder npc-default pg-auth">
    <div class="nk-app-root">
        <!-- main  -->
        <div class="nk-main ">
            <!-- wrap  -->
            <div class="nk-wrap nk-wrap-nosidebar">
                <!-- content  -->
                <div class="nk-content ">
                    @RenderBody()
                </div>
                <!-- wrap -->
            </div>
            <!-- content -->
        </div>
        <!-- main  -->
    </div>
    <!-- app-root -->
    <!-- JavaScript -->
    <!-- JavaScript -->
    <script src="~/js/bundle.js"></script>
    <script src="~/js/scripts.js"></script>
    <script src="~/js/dashboard/bundle.js"></script>
    <script src="~/js/dashboard/scripts.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>